### PR TITLE
fix: migrated samples to speech 2.0.0

### PR DESCRIPTION
**Pull request by b-loved-dreamer**
Started updating samples

### CODE REVIEW

**Comment by busunkim96** [comment]
Hmm, it looks like some of these already exist on master. Could you rebase your branch locally?

```
git checkout master
git pull origin master
git checkout speechmigration
git rebase master
```

**Comment by leahecole** [comment]
I'm working with him now over chat to do a rebase :)

**Review by telpirion — APPROVED** [review]

**Review by tmatsuo — APPROVED** [review]
LGTM

However, maybe it's easier to review if you separate the quote changes and the migration. Maybe next time.

**Comment by b-loved-dreamer** [comment]
@sirtorry, would you please review this PR.

**Review by sirtorry — APPROVED** [review]

**Pull request merged**
